### ISSUE TITLE
Why ignore some version

### ISSUE THREAD

**Issue by alpacaca** [drinkjava2/jDialects#19]
Some db version like MySQL5Dialect，MySQL55Dialect，MySQL57Dialect and MySQL8Dialect.
If I use MySQL56, which dialect should i choose? Does it backward compatible as I use MySQL57Dialect?

**Comment by drinkjava2** [comment]
Hi alpacaca, from here you can find the answer:
https://github.com/hibernate/hibernate-orm/tree/main/hibernate-core/src/main/java/org/hibernate/dialect
the reason is Hibernate have no MySQL56 dialect, so jDialects have no because jDialects copied all Hibernate's dialects.
If you open Hibernate source code of MySQL55Dialect and MySQL57Dialect you can see them all extend from MySQLDialect and have no any difference, so for your case you can use of one of below dialect, no difference:
MySQLDialect  or MySQL55Dialect  or MySQL57Dialect.

**Comment by alpacaca** [comment]
All right, thx
